update packages
zetonteam/zeton_react pull request #17
Opened 2021-02-23 20:54 UTC by zakonfeniksa

Update packages to latest versions.
https://imgur.com/a/KgPFeAo

2021-02-23 21:03 UTC, zakonfeniksa commented
@material-ui/core ^4.11.0 -> ^4.11.3
@testing-library/jest-dom ^4.2.4 -> ^5.11.9
@testing-library/react ^9.5.0 -> ^11.2.5
@testing-library/user-event ^7.2.1 -> ^12.7.3
nan ^2.14.1 -> ^2.14.2
react ^16.13.1 -> ^17.0.1
react-dom ^16.13.1 -> ^17.0.1
react-scripts 3.4.1 -> 4.0.3

2021-03-04 20:22 UTC, maknetaRo reviewed
Please merge develop to your branch first.

2021-03-04 20:23 UTC, maknetaRo reviewed
Brak pliku Dockerfile

2021-03-04 20:23 UTC, maknetaRo requested changes
Masz też na tej branchy plikie w src, których w nowej wersji już nie ma. W components powinny być tylko foldery: atoms, modules, pages, structures, templates. Zwróć na to uwagę przy mergowaniu developa do tej gałęzi.

2021-03-15 20:39 UTC, closed without merging